name: 'Auto Update Rubric Branches'
description: "Update rubric`s branch when master was pushed"

runs:
  using: 'composite'
  steps:
    - id: job
      continue-on-error: true
      shell: bash
      run: ${{ github.action_path }}/update.sh