name: 'Auto Update Rubric Branches'
description: "Update rubric`s branch when main branch was pushed"

inputs:
  source_branch:
    description: 'Source branch'
    default: main
  target_branches:
    description: 'Target rubric branches'
    default: rubrica rubrica-vazia rubrica-parcial rubrica-quebrando-lint
  target_label:
    description: 'Target PR label'
    default: 'rubrica'
  token:
    description: 'GitHub PAT token'
    required: true

runs:
  using: 'composite'
  steps:
    - id: job
      continue-on-error: true
      shell: bash
      run: export INPUT_TOKEN=${{ inputs.token }} && export INPUT_SOURCE_BRANCH=${{ inputs.source_branch }} && export INPUT_TARGET_LABEL=${{ inputs.target_label }} && export INPUT_TARGET_BRANCHES="${{ inputs.target_branches }}" && ${{ github.action_path }}/update.sh
